### PR TITLE
Remove dependency to members plugin

### PR DESCRIPTION
**Pull request by tschortsch**

### CODE REVIEW

**Comment by metaodi** [comment]
This would certainly work. I'm just wondering if we could find a way to use 'current_user_can' and check for a capability instead of a role. I guess the reason why it is discouraged by WordPress and the Members plugin is because on different instances, you could have different roles. But I don't know if there is a suitable capability to check for plus "Administrator" might actually be one of those roles that you'll find on any instance. What do you think?

**Comment by tschortsch** [comment]
Yeah checking against caps could really be a better choice since role names can change. WordPress does the following to check if a user is a super admin on a non-multisite (https://github.com/WordPress/WordPress/blob/master/wp-includes/capabilities.php#L719):
`$user->has_cap('delete_users')`

Maybe we should do the same.

**Comment by acorbi** [comment]
@metaodi @tschortsch As a potential adopter of your plugin, I would definitely prefer such a solution before having to integrate yet another plugin. 

Question: Besides having access to this function, what is the benefit of having the members plugin installed?

**Comment by tschortsch** [comment]
@acorbi The members plugin provides you a GUI to all the user roles and their capabilities. It just makes it possible to edit or create roles via the WordPress backend.

**Comment by metaodi** [comment]
@tschortsch why not use [`is_super_admin()`](https://codex.wordpress.org/Function_Reference/is_super_admin) directly? The codex says "Determine if user is a network (super) admin. Will also check if user is admin if network mode is disabled."

**Pull request merged**
